#!/usr/bin/env bash

export CONTECO_LABEL="module.schema_registry_sasl - ContEco"
export CONTECO_DESCRIPTION="The ContEco Confluent Schema Registry module. wtih SASL authentication."

export CONTECO_TYPE="module"
export CONTECO_NAME="schema_registry_sasl"
export CONTECO_TAG="6.0.0"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="image"
