#!/usr/bin/env bash

export CONTECO_LABEL="module.schema_registry_tocloud - ContEco"
export CONTECO_DESCRIPTION="The ContEco Confluent Schema Registry to cloud module with managed standard URL."

export CONTECO_TYPE="module"
export CONTECO_NAME="schema_registry_tocloud"
export CONTECO_TAG="5.4.0"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="image"
